# Generated by Django 5.1.3 on 2024-11-23 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='id_character',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='id_equip',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='team',
        ),
        migrations.AddField(
            model_name='character',
            name='inventaire',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.equipement'),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
