# Generated by Django 5.1.3 on 2024-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_rename_id_character_character_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
