# Generated by Django 5.1.3 on 2024-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_character_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='capacite',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
